[book]
title = "TND061"
authors = ["Eric"]
description = ""
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "docs"
create-missing = true

[output.html]
default-theme = "coal"
additional-css = ["src/css/custom.css", "src/css/highlight.css"]
no-section-label = true
git-repository-url = "https://github.com/eried124/eried124.github.io"

[output.html.print]
enable = false

[output.html.search]
enable = false
